# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     # Installing Node js
      - name: Installing Node Js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      # Pemisson
      - name: Setting Permission
        run : sudo npm install -g --unsafe-perm
        
        
      # Installing Yarn package manager
      -  name: Installing yarn
         uses: borales/actions-yarn@v2.0.0
         with:
           cmd: install
       # Build react app
      - name: Build React App
        run: yarn build
       
       # Installing surge
      - name: Installing surge
        run: npm install --global surge
        
       # deploying app on surge
      - name: Deploying on surge
        run: surge ./build quiz-app-ts-arsalan.surge.sh --token ${{ secrets.SURGE_TOKEN }}   
